version: '3.8'

services:
  smartrecruit-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8050:8050"
    depends_on:
      - smartrecruit-api