# Generated by Django 5.1.3 on 2025-07-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_title_jobdetail_role_remove_jobdetail_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('skill_type', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn URL of Candidate', null=True)),
                ('github', models.URLField(blank=True, help_text='Github URL of Candidate', null=True)),
                ('skills', models.ManyToManyField(help_text='Skills, Technologies, and Certifications', to='user.skill')),
            ],
        ),
    ]
