# Generated by Django 5.1.3 on 2025-07-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_skill_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.TextField(default='Not Specified', help_text='Skills, Technologies and Certifications Requirement'),
            preserve_default=False,
        ),
    ]
