# Generated by Django 5.1.3 on 2025-07-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_candidate_skills_candidate_soft_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(help_text="Name of the degree (e.g., Bachelor's in Computer Science)", max_length=255)),
                ('university_name', models.CharField(help_text='Name of the university or institution', max_length=255)),
                ('start_year', models.PositiveIntegerField(help_text='Start year of education')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='End year of education (null if ongoing)', null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='user.candidate')),
            ],
        ),
    ]
