# Generated by Django 5.1.3 on 2025-07-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_candidate_phone_number_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv_file',
        ),
    ]
