# Generated by Django 5.1.3 on 2025-07-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_jobapplication_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assign this job to an HR Manager', limit_choices_to={'role': 'hr_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='user.useraccount'),
        ),
    ]
