# Generated by Django 5.1.3 on 2025-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_jobdetail_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
