# Generated by Django 5.1.3 on 2025-07-16 19:32

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_mediaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaupload',
            name='file_type',
            field=models.CharField(default='Not Specified', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='job_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='cv',
            field=models.FileField(default='Not Specified', upload_to='cvs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
