# Generated by Django 5.1.3 on 2025-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_mediaupload_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('not_selected', 'Not Selected'), ('selected', 'Selected'), ('initial_screening', 'Initial Screening'), ('final_screening', 'Final Screening')], default='not_selected', max_length=20),
        ),
    ]
