# Generated by Django 5.1.3 on 2025-07-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='ai_recommendation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
