# Generated by Django 5.1.3 on 2025-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_jobapplication_media_id_delete_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
