# Generated by Django 5.1.3 on 2025-07-08 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='permission',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('full_admin', 'Full Admin'), ('basic_admin', 'Basic Admin'), ('advanced_admin', 'Advanced Admin'), ('hr_manager', 'HR Manager'), ('recruiter', 'Recruiter')], max_length=20),
        ),
    ]
