# Generated by Django 5.1.3 on 2025-07-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useraccount_permission_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(help_text='Summary of Role')),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('salary_period', models.CharField(choices=[('year', 'Per Year'), ('month', 'Per Month')], default='year', max_length=20)),
                ('education_level', models.CharField(help_text='Education Level Requirement', max_length=255)),
                ('skills', models.TextField(help_text='Skills, Technologies and Certifications Requirement')),
                ('experience_level', models.CharField(help_text='Experience Level Requirement', max_length=255)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(default='Not Specified', max_length=128),
            preserve_default=False,
        ),
    ]
