# Generated by Django 5.1.3 on 2025-07-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_jobdetail_useraccount_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetail',
            old_name='title',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='summary',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='description',
            field=models.TextField(default='Not Specified', help_text='Description of Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='industry',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
    ]
