# Generated by Django 5.1.3 on 2025-07-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_candidate_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.AddField(
            model_name='candidate',
            name='soft_skills',
            field=models.TextField(default='Not Specified', help_text='Communication skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='technical_skills',
            field=models.TextField(default='Not Specified', help_text='Technical skills'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('work_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='Job title or role', max_length=255)),
                ('company_name', models.CharField(help_text='Name of the company', max_length=255)),
                ('start_year', models.PositiveIntegerField(help_text='Start year of employment')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='End year of employment (null if current)', null=True)),
                ('summary', models.TextField(help_text='Summary of responsibilities and achievements')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='user.candidate')),
            ],
        ),
    ]
