# Generated by Django 5.1.3 on 2025-07-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_mediaupload_file_type_mediaupload_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='Assign this job to an HR Manager', limit_choices_to={'role': 'hr_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_by', to='user.useraccount'),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Assign this job to a Recruiter', limit_choices_to={'role': 'recruiter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='user.useraccount'),
        ),
    ]
