# Generated by Django 5.1.3 on 2025-07-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_jobdetail_posted_by_alter_jobdetail_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
