# Generated by Django 5.1.3 on 2025-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_jobapplication_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(default=' I am Student ', help_text='Introduction of Candidate'),
            preserve_default=False,
        ),
    ]
