# Generated by Django 5.1.3 on 2025-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_candidate_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cultural_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='technical_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
