# Generated by Django 5.1.3 on 2025-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_useraccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended')], default='Active', max_length=10),
        ),
    ]
