# Generated by Django 5.1.3 on 2025-07-21 21:46

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_jobdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='cv',
            field=models.FileField(upload_to=user.models.cv_upload_path),
        ),
    ]
