# Generated by Django 5.1.3 on 2025-07-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaupload',
            name='id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience',
            field=models.FloatField(default=0.0, help_text='Total years of professional experience'),
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='media_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_name',
            field=models.CharField(blank=True, help_text="Name of the degree (e.g., Bachelor's in Computer Science)", max_length=255),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(blank=True, help_text="End year of education (e.g., '2024' or 'Ongoing')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, help_text="Start year of education (e.g., '2020' or 'Present')", max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.CharField(blank=True, help_text='Name of the university or institution', max_length=255),
        ),
    ]
