# Generated by Django 5.1.3 on 2025-07-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_mediaupload_id_candidate_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='media_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),

    ]
