# Generated by Django 5.1.3 on 2025-08-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_feedback_processed_delete_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='media_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
